import './js/header';
import './js/gallery';
import './js/reviews';
import './js/faq';
import './js/privacy';
import './js/cookies';
import './js/pop-up';
import './js/how-to-play';
import './js/gallery';
